-- This is where inalizing and sample data will go


SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE TITLES;
TRUNCATE TABLE ADDRESSES;
TRUNCATE TABLE PERSONS;
TRUNCATE TABLE USER;
TRUNCATE TABLE PERSONNEL_TYPE;
SET REFERENTIAL_INTEGRITY TRUE;

