-- This is where inalizing and sample data will go


SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE REGISTER;
TRUNCATE TABLE CLASS;
TRUNCATE TABLE SALARIED_INSTRUCTOR;
TRUNCATE TABLE HOURLY_INSTRUCTOR;
TRUNCATE TABLE ROOM;
TRUNCATE TABLE EXERCISE;
TRUNCATE TABLE MEMBER;
TRUNCATE TABLE MEMBERSHIP;
TRUNCATE TABLE ROLES_PRIVILEGES;
TRUNCATE TABLE PRIVILEGE;
TRUNCATE TABLE USERS_ROLES;
TRUNCATE TABLE ROLE;
TRUNCATE TABLE USER;
SET REFERENTIAL_INTEGRITY TRUE;
