-- This is where inalizing and sample data will go


TRUNCATE TABLE REGISTER CASCADE;
TRUNCATE TABLE CLASS CASCADE;
TRUNCATE TABLE SALARIED_INSTRUCTOR CASCADE;
TRUNCATE TABLE HOURLY_INSTRUCTOR CASCADE;
TRUNCATE TABLE ROOM CASCADE;
TRUNCATE TABLE EXERCISE CASCADE;
TRUNCATE TABLE MEMBER CASCADE;
TRUNCATE TABLE MEMBERSHIP CASCADE;
TRUNCATE TABLE ROLES_PRIVILEGES CASCADE;
TRUNCATE TABLE PRIVILEGE CASCADE;
TRUNCATE TABLE USERS_ROLES CASCADE;
TRUNCATE TABLE ROLE CASCADE;
TRUNCATE TABLE PERSON CASCADE;

