
CREATE USER fitness WITH
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  NOREPLICATION
  PASSWORD 'fitness';
  
 
CREATE DATABASE fitness
    WITH 
    OWNER = fitness
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;
  
CREATE DATABASE fitness_test
    WITH 
    OWNER = fitness
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;
